### ISSUE TITLE
Write acceptance criteria for the first prototype

### ISSUE THREAD

**Issue by iamjessklein** [Gl0balKids/bocoup-gk-tool#3]
What is our framing question?
What is our proposed solution?

**Comment by brianloveswords** [comment]
_Goal_: Get Marshall to attend a follow up workshop
_Scenario_: Marshall is excited after finishing "Game Design 101" workshop at his afterschool. Marshall is at end of workshop.
_Given_: Marshall is excited about game design
_And_: Marshall is with Kelly for 5-10 mins
_When_: Kelly shows Marshall the app
_Then_: 
- Kelly and Marshall create a profile for Marshall. 
- Kelly and Marshall identify Marshall's preferences. 
- Marshall attends a follow-up workshop.

**Comment by iamjessklein** [comment]
:+1:  Adding this to the wiki.
